# Generated by Django 3.1.2 on 2020-10-24 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=75)),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=40)),
                ('img', models.ImageField(null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office_number', models.IntegerField(verbose_name='number')),
                ('in_which_building_is', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.building')),
            ],
        ),
        migrations.CreateModel(
            name='Workplace_off',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupied', models.BooleanField()),
                ('number_workplace', models.IntegerField(verbose_name='number_workplace')),
                ('which_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offices.office')),
            ],
        ),
        migrations.CreateModel(
            name='Reserved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='offices.workplace_off')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='offices.employee')),
            ],
        ),
    ]
